### ISSUE TITLE
About evaluate2.py

### ISSUE THREAD

**Issue by hcc0912** [lkku1/MODE#1]
When I run evaluate2.py, the following error occurs. Is there a problem with the code?
Traceback (most recent call last):
  File "F:\Hcc_2\MODE-main\evaluate2.py", line 129, in <module>
    main()
  File "F:\Hcc_2\MODE-main\evaluate2.py", line 112, in main
    outputs = model(equi_inputs, depth_patch, roll_idx, flip)
  File "C:\ProgramData\Anaconda3\envs\hcc_envs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Hcc_2\MODE-main\networks\Refine.py", line 84, in forward
    depth_init = pers2equi(depth_patch, self.fov, self.nrows, (self.patch_size, self.patch_size), (self.equi_h//4, self.equi_w//4), "pred_512_13", roll_idx, flip) #bs, 1, 512, 1024, 18
  File "F:\Hcc_2\MODE-main\networks\P2E.py", line 172, in pers2equi
    Ia = pers_img[:, :, y0, x0, z]
IndexError: too many indices for tensor of dimension 4
![QQ图片20240409172103](https://github.com/lkku1/MODE/assets/113153102/7c53f13b-93b2-4f78-b102-182f8b5e2659)

**Comment by lkku1** [comment]
I think there may be two possible reasons for this issue, one is that the shape of pers_img does not match, and the other is that the generation of "pred-512_13.pth" may have been incorrect.
1. Check the shape of pers_img
2. Generate a new "pred-512_13.pth"

**Comment by hcc0912** [comment]
> I think there may be two possible reasons for this issue, one is that the shape of pers_img does not match, and the other is that the generation of "pred-512_13.pth" may have been incorrect.
> 
> 1. Check the shape of pers_img
> 2. Generate a new "pred-512_13.pth"

I am using the 'pred-512_13.pth' file provided by you, so there shouldn't be any issue. I suspect it might be due to the shape of 'pers_img'. I want to know if you directly loaded the raw data using Matterport3d.py, or if there were any other operations involved. Because when I loaded the dataset according to your code and then ran evaluate2.py, the shape appeared to be different from the comments you provided.
![QQ图片20240409210232](https://github.com/lkku1/MODE/assets/113153102/989b0fd3-4c2a-45b4-b5e1-b1f92ccbd70b)

**Comment by lkku1** [comment]
Please  delete line 111 in evaluate2.py      depth_path = torch.unsqueeze(depth_patch, dim=0)

**Comment by hcc0912** [comment]
The code itself doesn't utilize the depth_path parameter, so deleting it doesn't seem to have changed the original execution; the same error persists.
![QQ图片20240410105917](https://github.com/lkku1/MODE/assets/113153102/4c8d565e-88ff-4ea9-a093-c55e3ee73933)
I have thought that there might be an issue with the operations on depth_patch_map in Refine.py.
![Uploading QQ图片20240410110432.png…]()

**Comment by hcc0912** [comment]
The code itself doesn't utilize the depth_path parameter, so deleting it doesn't seem to have changed the original execution; the same error persists.
![QQ图片20240410105917](https://github.com/lkku1/MODE/assets/113153102/23415d64-0afb-40ba-992b-53507a4f63ae)
I have thought that there might be an issue with the operations on depth_patch_map in Refine.py.
![QQ图片20240410110432](https://github.com/lkku1/MODE/assets/113153102/9287a585-e41b-4962-bfec-91961f8d00c5)

**Comment by lkku1** [comment]
We don't have any additional operations.
This is the relevant parameter for our runtime.
![pp](https://github.com/lkku1/MODE/assets/43928695/a044f083-ee4e-46ff-a017-89908d1c21ba)

**Comment by lkku1** [comment]
We did not upload pred-512_13. pth
After the above modifications, the incorrect pred-512_13. pth may also cause this error
We will then upload this file

**Comment by hcc0912** [comment]
> We did not upload pred-512_13. pth After the above modifications, the incorrect pred-512_13. pth may also cause this error We will then upload this file


Could you please grant access to the permission of pred_512_13 for me? I encountered access denial when attempting to access it. Thank you.
![QQ图片20240410161027](https://github.com/lkku1/MODE/assets/113153102/f853d40e-9784-4d21-a0b4-a1ecb75e6b13)

**Comment by lkku1** [comment]
We have uploaded pred-512_13.pth. Now you can download it

**Comment by hcc0912** [comment]
> We have uploaded pred-512_13.pth. Now you can download it

First of all, thank you very much for all your previous answers. Additionally, I was wondering if I could trouble you to provide the complete code, including the train.py, etc. I'd like to fully implement your research contribution.

**Comment by lkku1** [comment]
You can refer to the training methods in https://github.com/alibaba/UniFuse-Unidirectional-Fusion

**Comment by hcc0912** [comment]
> You can refer to the training methods in https://github.com/alibaba/UniFuse-Unidirectional-Fusion

Could you please provide the relevant code for the loss function?
